name: Deploy Next.js App to VPS

on:
  push:
    branches:
      - deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # ১. প্রজেক্ট ফোল্ডারে যাওয়া
            cd ~/Portfolio

            # ২. গিট পুল, ইনস্টল ও বিল্ড
            git pull origin deployment
            npm install
            npm run build

            # ৩. সরাসরি PM2 দিয়ে রিস্টার্ট
            pm2 restart portfolio